*** Starting uWSGI 2.0.15-debian (64bit) on [Tue Mar 15 11:21:48 2022] ***
compiled with version: 7.5.0 on 26 August 2021 18:40:50
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /usr/bin/uwsgi-core
dropping root privileges as early as possible
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
dropping root privileges after socket binding
dropping root privileges after plugin initialization
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
*** no app loaded. going in full dynamic mode ***
dropping root privileges after application loading
*** uWSGI is running in multiple interpreter mode ***
!!!!!!!!!!!!!! WARNING !!!!!!!!!!!!!!
no request plugin is loaded, you will not be able to manage requests.
you may need to install the package for your language of choice, or simply load it with --plugin.
!!!!!!!!!!! END OF WARNING !!!!!!!!!!
spawned uWSGI worker 1 (and the only) (pid: 26189, cores: 1)
-- unavailable modifier requested: 0 --
-- unavailable modifier requested: 0 --
-- unavailable modifier requested: 0 --
-- unavailable modifier requested: 0 --
-- unavailable modifier requested: 0 --
*** Starting uWSGI 2.0.15-debian (64bit) on [Tue Mar 15 11:26:53 2022] ***
compiled with version: 7.5.0 on 26 August 2021 18:40:50
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /usr/bin/uwsgi-core
dropping root privileges as early as possible
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
dropping root privileges after socket binding
Python version: 3.6.9 (default, Dec  8 2021, 21:08:43)  [GCC 8.4.0]
Set PythonHome to /home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007ff7a49a95c0 (most recent call first):
*** Starting uWSGI 2.0.15-debian (64bit) on [Tue Mar 15 11:31:52 2022] ***
compiled with version: 7.5.0 on 26 August 2021 18:40:50
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /usr/bin/uwsgi-core
dropping root privileges as early as possible
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
dropping root privileges after socket binding
Python version: 3.6.9 (default, Dec  8 2021, 21:08:43)  [GCC 8.4.0]
PEP 405 virtualenv detected: /home/spidercore/develop/flask-dev2/venv
Set PythonHome to /home/spidercore/develop/flask-dev2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55a5756aa5c0
dropping root privileges after plugin initialization
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./hello.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
dropping root privileges after application loading
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 8263, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/1] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 11:31:59 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/2] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 11:31:59 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15-debian (64bit) on [Tue Mar 15 15:15:17 2022] ***
compiled with version: 7.5.0 on 26 August 2021 18:40:50
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /usr/bin/uwsgi-core
dropping root privileges as early as possible
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5490 fd 3
dropping root privileges after socket binding
Python version: 3.6.9 (default, Dec  8 2021, 21:08:43)  [GCC 8.4.0]
PEP 405 virtualenv detected: /home/spidercore/develop/flask-dev2/venv
Set PythonHome to /home/spidercore/develop/flask-dev2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x5622ef2ae5c0
dropping root privileges after plugin initialization
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "./hello.py", line 1, in <module>
    from flask import Flask
ModuleNotFoundError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
dropping root privileges after application loading
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 23382, cores: 1)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/3] 172.16.0.1 () {42 vars in 818 bytes} [Tue Mar 15 15:15:27 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/4] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:15:27 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15-debian (64bit) on [Tue Mar 15 15:17:33 2022] ***
compiled with version: 7.5.0 on 26 August 2021 18:40:50
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /usr/bin/uwsgi-core
dropping root privileges as early as possible
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (:5490).
bind(): Address already in use [core/socket.c line 769]
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/5] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:11 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/6] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:11 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/7] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:13 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/8] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:13 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/9] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:14 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/10] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:14 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/11] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:14 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/12] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:14 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/13] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:15 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/14] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:15 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/15] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:15 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/16] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:15 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/17] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:15 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/18] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:15 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/19] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:18:15 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/20] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:18:15 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.15-debian (64bit) on [Tue Mar 15 15:21:25 2022] ***
compiled with version: 7.5.0 on 26 August 2021 18:40:50
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /usr/bin/uwsgi-core
dropping root privileges as early as possible
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address :5490 fd 3
dropping root privileges after socket binding
Python version: 3.6.9 (default, Dec  8 2021, 21:08:43)  [GCC 8.4.0]
Set PythonHome to /home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fb4e45125c0 (most recent call first):
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/21] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 15:21:33 2022] GET / => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
--- no python application found, check your startup logs for errors ---
[pid: 8263|app: -1|req: -1/22] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 15:21:33 2022] GET /favicon.ico => generated 21 bytes in 0 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
*** Starting uWSGI 2.0.20 (64bit) on [Tue Mar 15 16:52:21 2022] ***
compiled with version: 9.4.0 on 22 December 2021 18:20:43
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /home/spidercore/miniconda3/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
Python version: 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 02:08:29)  [GCC 9.4.0]
Set PythonHome to /home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages
Python path configuration:
  PYTHONHOME = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  PYTHONPATH = (not set)
  program name = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/bin/python'
  sys.base_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.base_exec_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.executable = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/bin/python'
  sys.prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.exec_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.path = [
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/lib/python38.zip',
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/lib/python3.8',
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f91aa903b80 (most recent call first):
<no Python frame>
*** Starting uWSGI 2.0.20 (64bit) on [Tue Mar 15 16:53:17 2022] ***
compiled with version: 9.4.0 on 22 December 2021 18:20:43
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /home/spidercore/miniconda3/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
Python version: 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 02:08:29)  [GCC 9.4.0]
Set PythonHome to /home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages
Python path configuration:
  PYTHONHOME = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  PYTHONPATH = (not set)
  program name = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/bin/python'
  sys.base_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.base_exec_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.executable = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/bin/python'
  sys.prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.exec_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages'
  sys.path = [
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/lib/python38.zip',
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/lib/python3.8',
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f567930bb80 (most recent call first):
<no Python frame>
*** Starting uWSGI 2.0.20 (64bit) on [Tue Mar 15 16:54:34 2022] ***
compiled with version: 9.4.0 on 22 December 2021 18:20:43
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /home/spidercore/miniconda3/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
Python version: 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 02:08:29)  [GCC 9.4.0]
Set PythonHome to /home/spidercore/develop/flask-dev2/venv/lib/python3.8
Python path configuration:
  PYTHONHOME = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8'
  PYTHONPATH = (not set)
  program name = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/bin/python'
  sys.base_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8'
  sys.base_exec_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8'
  sys.executable = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/bin/python'
  sys.prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8'
  sys.exec_prefix = '/home/spidercore/develop/flask-dev2/venv/lib/python3.8'
  sys.path = [
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/lib/python38.zip',
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/lib/python3.8',
    '/home/spidercore/develop/flask-dev2/venv/lib/python3.8/lib/python3.8/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f7efe9a3b80 (most recent call first):
<no Python frame>
*** Starting uWSGI 2.0.20 (64bit) on [Tue Mar 15 16:56:23 2022] ***
compiled with version: 9.4.0 on 22 December 2021 18:20:43
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /home/spidercore/miniconda3/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
Python version: 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 02:08:29)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/spidercore/develop/flask-dev2/venv
Set PythonHome to /home/spidercore/develop/flask-dev2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x558536e70160
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x558536e70160 pid: 12806 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 12806, cores: 1)
[pid: 12806|app: 0|req: 1/1] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:28 2022] GET / => generated 11 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (2 switches on core 0)
[pid: 12806|app: 0|req: 2/2] 172.16.0.1 () {42 vars in 777 bytes} [Tue Mar 15 16:56:28 2022] GET /favicon.ico => generated 232 bytes in 1 msecs (HTTP/1.1 404) 2 headers in 87 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 3/3] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:58 2022] GET / => generated 11 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 4/4] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:58 2022] GET / => generated 11 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 5/5] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:59 2022] GET / => generated 11 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 6/6] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:59 2022] GET / => generated 11 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 7/7] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:59 2022] GET / => generated 11 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 8/8] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:59 2022] GET / => generated 11 bytes in 0 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 9/9] 172.16.0.1 () {44 vars in 849 bytes} [Tue Mar 15 16:56:59 2022] GET / => generated 11 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 10/10] 172.16.0.1 () {42 vars in 818 bytes} [Tue Mar 15 16:57:30 2022] GET / => generated 11 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
[pid: 12806|app: 0|req: 11/11] 172.16.0.1 () {42 vars in 826 bytes} [Tue Mar 15 16:57:36 2022] GET /meet => generated 16 bytes in 1 msecs (HTTP/1.1 200) 2 headers in 79 bytes (1 switches on core 0)
*** Starting uWSGI 2.0.20 (64bit) on [Thu Mar 17 11:34:50 2022] ***
compiled with version: 9.4.0 on 22 December 2021 18:20:43
os: Linux-5.4.0-94-generic #106~18.04.1-Ubuntu SMP Fri Jan 7 07:23:53 UTC 2022
nodename: RTXTITANx2
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 28
current working directory: /home/spidercore/develop/flask-dev2
detected binary path: /home/spidercore/miniconda3/bin/uwsgi
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 1029635
your memory page size is 4096 bytes
detected max file descriptor number: 65536
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to UNIX address /home/spidercore/develop/flask-dev2/uwsgi.sock fd 3
Python version: 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 02:08:29)  [GCC 9.4.0]
PEP 405 virtualenv detected: /home/spidercore/develop/flask-dev2/venv
Set PythonHome to /home/spidercore/develop/flask-dev2/venv
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x55eb969cf160
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72920 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x55eb969cf160 pid: 16588 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 16588, cores: 1)
[2022-03-17 11:34:59,049] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/spidercore/develop/flask-dev2/./application.py", line 21, in hello_world
    print(param_dict['source'])
KeyError: 'source'
[pid: 16588|app: 0|req: 1/1] 172.16.0.1 () {42 vars in 818 bytes} [Thu Mar 17 11:34:59 2022] GET / => generated 290 bytes in 3 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 2/2] 172.16.0.1 () {42 vars in 878 bytes} [Thu Mar 17 12:43:08 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 242 msecs (HTTP/1.1 200) 3 headers in 107 bytes (4 switches on core 0)
{"type":"protein","name":"tetra"}
[pid: 16588|app: 0|req: 3/3] 172.16.0.1 () {42 vars in 886 bytes} [Thu Mar 17 16:29:50 2022] GET /?source=%7B%22type%22:%22protein%22,%22name%22:%22tetra%22%7D&source_content_type=application%2Fjson => generated 106947 bytes in 120 msecs (HTTP/1.1 200) 3 headers in 107 bytes (1 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 4/4] 175.209.198.249 () {42 vars in 885 bytes} [Thu Mar 17 18:22:51 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 221 msecs (HTTP/1.1 200) 3 headers in 107 bytes (4 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 5/5] 175.209.198.249 () {42 vars in 885 bytes} [Thu Mar 17 18:23:17 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 115 msecs (HTTP/1.1 200) 3 headers in 107 bytes (3 switches on core 0)
{"type":"drug","name":"asprin"}
[pid: 16588|app: 0|req: 6/6] 172.16.0.1 () {42 vars in 871 bytes} [Thu Mar 24 16:50:04 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22asprin%22%7D&source_content_type=application%2Fjson => generated 3 bytes in 81 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{"type":"drug","name":"covid"}
[pid: 16588|app: 0|req: 7/7] 172.16.0.1 () {42 vars in 869 bytes} [Thu Mar 24 16:50:12 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22covid%22%7D&source_content_type=application%2Fjson => generated 3 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{"type":"drug","name":"aspirin"}
[pid: 16588|app: 0|req: 8/8] 172.16.0.1 () {42 vars in 873 bytes} [Thu Mar 24 16:50:19 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22aspirin%22%7D&source_content_type=application%2Fjson => generated 3 bytes in 8 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{"type":"drug","name":"acetylsalicylic"}
[pid: 16588|app: 0|req: 9/9] 172.16.0.1 () {42 vars in 889 bytes} [Thu Mar 24 16:50:36 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acetylsalicylic%22%7D&source_content_type=application%2Fjson => generated 470451 bytes in 123 msecs (HTTP/1.1 200) 3 headers in 107 bytes (3 switches on core 0)
{"type":"drug","name":"covid"}
[pid: 16588|app: 0|req: 10/10] 175.209.198.154 () {42 vars in 892 bytes} [Wed Mar 30 17:49:29 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22covid%22%7D&source_content_type=application%2Fjson => generated 3 bytes in 83 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 11/11] 175.209.198.154 () {42 vars in 890 bytes} [Wed Mar 30 18:22:11 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 184 msecs (HTTP/1.1 200) 3 headers in 107 bytes (4 switches on core 0)
{"type":"disease","name":"covid"}
[pid: 16588|app: 0|req: 12/12] 175.209.198.154 () {42 vars in 898 bytes} [Wed Mar 30 18:22:31 2022] GET /?source=%7B%22type%22:%22disease%22,%22name%22:%22covid%22%7D&source_content_type=application%2Fjson => generated 8152 bytes in 15 msecs (HTTP/1.1 200) 3 headers in 105 bytes (1 switches on core 0)
{"type":"chemical","name":"tetra"}
[pid: 16588|app: 0|req: 13/13] 175.209.198.154 () {42 vars in 900 bytes} [Wed Mar 30 18:22:47 2022] GET /?source=%7B%22type%22:%22chemical%22,%22name%22:%22tetra%22%7D&source_content_type=application%2Fjson => generated 13298 bytes in 132 msecs (HTTP/1.1 200) 3 headers in 106 bytes (1 switches on core 0)
{"type":"chemical","name":"asprin"}
[pid: 16588|app: 0|req: 14/14] 175.209.198.154 () {42 vars in 902 bytes} [Wed Mar 30 18:23:03 2022] GET /?source=%7B%22type%22:%22chemical%22,%22name%22:%22asprin%22%7D&source_content_type=application%2Fjson => generated 3 bytes in 9 msecs (HTTP/1.1 200) 3 headers in 102 bytes (1 switches on core 0)
{"type":"chemical","name":"aspirin"}
[pid: 16588|app: 0|req: 15/15] 175.209.198.154 () {42 vars in 904 bytes} [Wed Mar 30 18:23:09 2022] GET /?source=%7B%22type%22:%22chemical%22,%22name%22:%22aspirin%22%7D&source_content_type=application%2Fjson => generated 30935 bytes in 18 msecs (HTTP/1.1 200) 3 headers in 106 bytes (1 switches on core 0)
{"type":"mRNA","name":"cel-let-7"}
[pid: 16588|app: 0|req: 16/16] 175.209.198.154 () {42 vars in 900 bytes} [Wed Mar 30 18:23:27 2022] GET /?source=%7B%22type%22:%22mRNA%22,%22name%22:%22cel-let-7%22%7D&source_content_type=application%2Fjson => generated 15813 bytes in 23 msecs (HTTP/1.1 200) 3 headers in 106 bytes (1 switches on core 0)
{"type":"drug","name":"acid"}
[2022-04-02 20:45:34,943] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/spidercore/develop/flask-dev2/./application.py", line 28, in hello_world
    res = qb.searchDrugInfo(inputName)
  File "/home/spidercore/develop/flask-dev2/./QueryBundle.py", line 64, in searchDrugInfo
    res = query(es, indexDrug, name)
  File "/home/spidercore/develop/flask-dev2/./QueryBundle.py", line 40, in query
    res = es.search(index=index, body=body)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3696, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: ProtocolError(('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))))
[pid: 16588|app: 0|req: 17/17] 175.209.198.154 () {42 vars in 890 bytes} [Sat Apr  2 20:45:34 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 290 bytes in 69 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
{"type":"disease","name":"covid"}
[2022-04-02 20:45:42,054] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/spidercore/develop/flask-dev2/./application.py", line 31, in hello_world
    res = qb.searchDiseaseInfo(inputName)
  File "/home/spidercore/develop/flask-dev2/./QueryBundle.py", line 77, in searchDiseaseInfo
    res = es.search(index=indexDisease, body=body)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3696, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9db8ad2c40>: Failed to establish a new connection: [Errno 111] Connection refused))
[pid: 16588|app: 0|req: 18/18] 175.209.198.154 () {42 vars in 898 bytes} [Sat Apr  2 20:45:42 2022] GET /?source=%7B%22type%22:%22disease%22,%22name%22:%22covid%22%7D&source_content_type=application%2Fjson => generated 290 bytes in 14 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
{"type":"drug","name":"acid"}
[2022-04-02 20:48:27,224] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/spidercore/develop/flask-dev2/./application.py", line 28, in hello_world
    res = qb.searchDrugInfo(inputName)
  File "/home/spidercore/develop/flask-dev2/./QueryBundle.py", line 64, in searchDrugInfo
    res = query(es, indexDrug, name)
  File "/home/spidercore/develop/flask-dev2/./QueryBundle.py", line 40, in query
    res = es.search(index=index, body=body)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3696, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9db8ad2490>: Failed to establish a new connection: [Errno 111] Connection refused))
[pid: 16588|app: 0|req: 19/19] 175.209.198.154 () {42 vars in 890 bytes} [Sat Apr  2 20:48:27 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 290 bytes in 13 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
{"type":"drug","name":"acid"}
[2022-04-03 09:32:43,881] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/spidercore/develop/flask-dev2/./application.py", line 28, in hello_world
    res = qb.searchDrugInfo(inputName)
  File "/home/spidercore/develop/flask-dev2/./QueryBundle.py", line 64, in searchDrugInfo
    res = query(es, indexDrug, name)
  File "/home/spidercore/develop/flask-dev2/./QueryBundle.py", line 40, in query
    res = es.search(index=index, body=body)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 3696, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: ConnectionError(Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f9db87e78b0>: Failed to establish a new connection: [Errno 111] Connection refused))
[pid: 16588|app: 0|req: 20/20] 175.209.198.249 () {42 vars in 891 bytes} [Sun Apr  3 09:32:43 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 290 bytes in 14 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
[2022-04-04 10:52:04,390] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spidercore/develop/flask-dev2/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/spidercore/develop/flask-dev2/./application.py", line 21, in hello_world
    print(param_dict['source'])
KeyError: 'source'
[pid: 16588|app: 0|req: 21/21] 192.168.0.3 () {40 vars in 727 bytes} [Mon Apr  4 10:52:04 2022] GET / => generated 290 bytes in 2 msecs (HTTP/1.1 500) 2 headers in 99 bytes (1 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 22/22] 172.16.0.1 () {42 vars in 874 bytes} [Mon Apr 11 21:42:54 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 161 msecs (HTTP/1.1 200) 3 headers in 107 bytes (3 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 23/23] 175.209.198.154 () {42 vars in 870 bytes} [Mon Apr 11 21:43:33 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 127 msecs (HTTP/1.1 200) 3 headers in 107 bytes (4 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 24/24] 172.16.0.1 () {42 vars in 874 bytes} [Tue Apr 12 10:52:07 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 222 msecs (HTTP/1.1 200) 3 headers in 107 bytes (3 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 25/25] 172.16.0.1 () {42 vars in 874 bytes} [Tue Apr 12 10:53:43 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 121 msecs (HTTP/1.1 200) 3 headers in 107 bytes (3 switches on core 0)
{"type":"drug","name":"acid"}
[pid: 16588|app: 0|req: 26/26] 172.16.0.1 () {42 vars in 874 bytes} [Wed Apr 13 20:44:36 2022] GET /?source=%7B%22type%22:%22drug%22,%22name%22:%22acid%22%7D&source_content_type=application%2Fjson => generated 626670 bytes in 204 msecs (HTTP/1.1 200) 3 headers in 107 bytes (3 switches on core 0)
